// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileUpload(arg1) {
  return window['go']['main']['App']['FileUpload'](arg1);
}

export function GetAllMatics() {
  return window['go']['main']['App']['GetAllMatics']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveMatic(arg1, arg2) {
  return window['go']['main']['App']['SaveMatic'](arg1, arg2);
}
