// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FileUpload(arg1:string):Promise<number>;

export function GetAllMatics():Promise<main.Response>;

export function GetMaticById(arg1:number):Promise<main.Response>;

export function Greet(arg1:string):Promise<string>;

export function RunMatic(arg1:string):Promise<void>;

export function SaveMatic(arg1:string,arg2:string):Promise<main.Response>;

export function SaveXML(arg1:number,arg2:string):Promise<main.Response>;
