// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FileUpload(arg1:string):Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function SaveMatic(arg1:string,arg2:string):Promise<main.Response>;
